apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8project
spec:
  replicas: 2
  selector:
    matchLabels:
      app: k8project
  template:
    metadata:
      labels:
        app: k8project
    spec:
      containers:
      - name: k8project
        image: 625834966565.dkr.ecr.ap-southeast-1.amazonaws.com/k8project-latest:latest
        ports:
        - containerPort: 3000
